version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
    - test
  web:
    restart: on-failure
    build: ./web
    networks: 
    - test
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    networks:
    - test
    depends_on:
    - web
networks:
  test:
    
